name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "working-demo-v1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v2.2.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/seb-sps-gui:demo-testing
