name: Build and Push to Docker Hub

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push: 
    tags:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag_suffix: ["", "-single-host"]
        include:
          - tag_suffix: ""
            path_name: ""
          - tag_suffix: "-single-host"
            path_name: "/sps-gui"

    steps:
    - name: Set env for dynamic tag
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')      
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}${{ matrix.tag_suffix }}" >> $GITHUB_ENV

    - name: Set env manual
      if: github.event_name == 'workflow_dispatch'
      run: echo "TAG_NAME=default_version${{ matrix.tag_suffix }}" >> $GITHUB_ENV
    
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
          username: naritter
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        push: true
        tags: docker.io/naritter/seb-sps-gui:${{ env.TAG_NAME }}
        build-args: VITE_SUB_PATH=${{ matrix.path_name }}