name: Build and Push to Docker Hub

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push: 
    tags:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Set env for dynamic tag
      if: github.event_name != 'workflow_dispatch'
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set env manual
      if: github.event_name == 'workflow_dispatch'
      run: echo "TAG_NAME=default_version" >> $GITHUB_ENV
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v2.2.0
      with:
          username: naritter
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: docker.io/naritter/seb-sps-gui:${{ env.TAG_NAME }}
